### ISSUE TITLE
How can I train from a checkpoint? 

### ISSUE THREAD

**Issue by chocolatedesue** [zassou65535/VITS#1]
I  read through the code and only find that vits_generator can be load from checkpoint while vits_discriminator can not  do it.

How can I handle it?

**Comment by chocolatedesue** [comment]
Ok, I do it.

I miscode the name of object and it works now.

**Comment by zassou65535** [comment]
Thank you for your interest in my repository.
The "vits_train.py" don't contain a function to load a checkpoint.
If you'd like to load it, I recommend to add some code to load.
