### ISSUE TITLE
the source wav and the target wav must is seen speaker?

### ISSUE THREAD

**Issue by 15755841658** [zassou65535/VITS#2]
hello! 
the code about the vits VOICE CONVERSION, 
the source wav and the target wav must is seen speaker?

**Comment by zassou65535** [comment]
Yeah, the source wav and the target wav must be seen speaker.
Thank you for your interest in my repository.

**Comment by 15755841658** [comment]
Thank you for your reply！en...  the source wav and the target wav can be unseen speaker, or the the source wav can be unseen speaker and the target wav can be seen speaker?  and what do I need to do?  Can you give me some advice？

**Comment by 15755841658** [comment]
@zassou65535

**Comment by zassou65535** [comment]
Unfortunately, VITS cannot handle unseen speakers. So my implementation of repository can deal with only seen speakers.
If you'd like handle unseen speakers, I recommend using another method that is not VITS.
